sources:
  - company: "Octiva"
    url: "https://octiva.tech/jobs/"
  - company: "Tabaknatie"
    url: "https://tabaknatie.be/vacancies/"
  - company: "Pionira"
    url: "https://pionira.be/vacatures/"
  - company: "Olympus Mobility"
    url: "https://www.olympus-mobility.be/nl/over-olympus-mobility/vacatures"
  - company: "Emma\u00fcs ICT"
    url: "https://ict-emmaus.cvw.io/?lang=nl-BE"
  - company: "Warren"
    url: "https://www.warren.eu/nl/about/careers"
  - company: "Robovision"
    url: "https://robovision.ai/about-us/careers"
  - company: "Ads & Data"
    url: "https://jobs.adsanddata.be/"
  - company: "Cartamundi"
    url: "https://cartamundi.com/careers"
  - company: "Reynaers Aluminium"
    url: "https://www.reynaers.com/careers"
  - company: "Groot Groter Groots"
    url: "https://www.grootgrotergroots.be/nl-be/jobs/"
  - company: "Indaver"
    url: "https://indaver.com/careers/our-vacancies/vacancies-belgium"
  - company: "Brady"
    url: "https://brady.hr-technologies.com/front/nl/vacancies"
  - company: "Twipe"
    url: "https://www.twipemobile.com/careers/"
  - company: "VITO"
    url: "https://vito.be/nl/jobs#paragraph-16553"
  - company: "DPG Media"
    url: "https://www.dpgmediagroup.com/nl-BE/werken-bij-ons/alle-vacatures"
  - company: "Remmicom"
    url: "https://jobs.remmicom.be/jobs/"
  - company: "Flowtribe"
    url: "https://www.flowtribe.io/jobs"
  - company: "H.Essers"
    url: "https://jobs.essers.com/nl-be/vacatures/"
  - company: "T\u00dcV Austria"
    url: "https://be.tuvaustria.com/jobs/"
  - company: "Qover"
    url: "https://www.qover.com/careers#jobs"
  - company: "Qargo"
    url: "https://careers.qargo.com/jobs?split_view=false&query=&country=Belgium"
  - company: "MSC"
    url: "https://msc.csod.com/ux/ats/careersite/4/home?c=msc&country=be"
  - company: "Vanheede"
    url: "https://jobs.vanheede.com/nl"
  - company: "Vanden Broele"
    url: "https://www.vandenbroele.be/jobs#jobsection"
  - company: "Unilin"
    url: "https://jobs.unilin.com/nl-be/jobs?filter=jobcode.eq.is&page=1&page_size=12&view_size=12"
  - company: "Picanol"
    url: "https://www.picanol.be/nl/jobs/vind-een-job"
  - company: "Greenyard"
    url: "https://careers-greenyard.cvw.io/?lang=nl-NL&section=ac930450-2270-c738-a2af-a1f62c945c93"
  - company: "Pelckmans"
    url: "https://jobs.pelckmans.be/nl"
  - company: "Aertssen"
    url: "https://jobs.aertssen.be/vacatures/"
  - company: "BrightAnalytics"
    url: "https://jobs.brightanalytics.eu/jobs?query=&country=Belgium"
  - company: "Renson"
    url: "https://jobs.renson.be/nl/vacatures"
    - company: "Smet Group"
    url: "https://jobs.smetgroup.be/nl"
  - company: "CNH Industrial Belgium"
    url: "https://www.cnhind-belgium.be/nl#vacatures"
  - company: "Deceuninck"
    url: "https://jobpage.cvwarehouse.com/?companyGuid=cb68e829-440c-495d-ba3d-68cf7aeb7f8a&lang=nl-BE"
  - company: "Jacops"
    url: "https://jobs.jacops.be/nl"
  - company: "GeoDynamics"
    url: "https://jobs.geodynamics.be/vacatures/"
  - company: "CW Logistics"
    url: "https://www.cwlogistics.be/nl/jobs"
  - company: "Jet Import"
    url: "https://jobs.jetimport.be/nl"
  - company: "Duco"
    url: "https://jobs.duco.eu/?lang=nl-BE&section=2a8e1887-db4b-b3f8-e585-34a634849f3a"
  - company: "Valtech Group"
    url: "https://jobs.valtechgroup.eu/nl"
  - company: "ScioTeq"
    url: "https://scioteq.recruitee.com/"
  - company: "Vandewiele"
    url: "https://vandewiele.com/careers/open-vacancies?specialisations=&types=&locations=belgium&brands="
  - company: "Baronie"
    url: "https://www.baronie.com/nl/vacatures"
  - company: "Locinox"
    url: "https://jobs.locinox.com/#Departementen"
  - company: "Zorgi"
    url: "https://zorgicareers.be/l/nl/vacatures"
  - company: "Smappee"
    url: "https://www.smappee.com/be-nl/jobs"
